title: Vis Motrix
description: Blog
author: Vis Motrix.
avatar: /yerko1.jpg
email: Corvina778j@gmail.com
location: Santiago, Chile.
skin: sunrise
math: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
#logo: logo.png
#social:
 # name: Yerko-Aj Novoa.
  #links:
   # - https://twitter.com/
   # - https://www.facebook.com/
   # - https://github.com/
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es

plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
